ARG PHP_VERSION=8
FROM php:${PHP_VERSION}-fpm
LABEL org.opencontainers.image.description="PHP base image with commonly used extensions pre-installed" \
     "com.koalaphils.vendor"="Koala Software Technology Innovations" \
     "com.koalaphils.image.author"="mdprotacio@outlook.com"

COPY --from=ghcr.io/php/pie:bin /pie /usr/bin/pie
ENV DEBIAN_FRONTEND=noninteractive
ENV COMPOSER_ALLOW_SUPERUSER=1

# Dependencies for building PHP extensions
# Add dependencies for PIE
ENV PHPIZE_DEPS="${PHPIZE_DEPS} autoconf automake build-essential gcc git libtool m4 make"

# Fixes for apt-get hash sum mismatch errors
RUN { \
      echo 'Acquire::Retries "5";'; \
      echo 'Acquire::http::Timeout "60";'; \
      echo 'Acquire::https::Timeout "60";'; \
      echo 'Acquire::http::No-Cache "true";'; \
      echo 'Acquire::http::Pipeline-Depth "0";'; \
      echo 'Acquire::ForceIPv4 "true";'; \
    } > /etc/apt/apt.conf.d/99fix-hashmismatch

# Install dependencies
RUN set -eux; \
    apt-get clean; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
# Add helper tools for development \
        curl \
        gettext-base \
        locales \
        netcat-traditional \
        wget \
# Add SSL support \
        ca-certificates \
        gnupg \
        openssl \
# PHP extension dependencies \
        `apt-cache pkgnames libavif | sort -V | head -1` \
        `apt-cache pkgnames libc6 | sort -V | head -1` \
        `apt-cache pkgnames libc-ares | sort -V | head -1` \
        `apt-cache pkgnames libcurl4 | sort -V | head -1` \
        `apt-cache pkgnames libfreetype | sort -V | head -1` \
        `apt-cache pkgnames libicu | grep -v "java" | sort -V | head -1` \
        `apt-cache pkgnames libjpeg | sort -V | head -1` \
        `apt-cache pkgnames libmagickcore | grep headers | sort | head -1` \
        `apt-cache pkgnames libmagickwand | grep headers | sort | head -1` \
        `apt-cache pkgnames libmcrypt | sort -V | head -1` \
        `apt-cache pkgnames libmemcache | sort -V | head -1` \
        `apt-cache pkgnames libmsgpack | sort -V | head -1` \
        `apt-cache pkgnames libpng | sort -V | head -1` \
        `apt-cache pkgnames libsqlite3 | sort -V | head -1` \
        `apt-cache pkgnames libwebp | sort -V | head -1` \
        `apt-cache pkgnames libzip | grep -v "java" | sort -V | head -1` \
        `apt-cache pkgnames unixodbc | sort -V | head -1` \
        `apt-cache pkgnames zlib | sort -V | head -1` \
    && \
    apt-get dist-clean

# Install PHP extension build dependencies
RUN set -eux; \
    savedAptMark="$(apt-mark showmanual)"; \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        $PHPIZE_DEPS \
        libicu-dev \
        libmagickcore-dev \
        libmagickwand-dev \
        libmemcached-dev \
        libmsgpack-dev \
        libpng-dev \
        libssl-dev \
        `apt-cache pkgnames libavif | grep dev | sort | head -1` \
        `apt-cache pkgnames libc6 | grep dev | sort | head -1` \
        `apt-cache pkgnames libc-ares | grep dev | sort | head -1` \
        `apt-cache pkgnames libfreetype | grep dev | sort -V | head -1` \
        `apt-cache pkgnames libjpeg | grep dev | sort -V | head -1` \
        `apt-cache pkgnames libmcrypt | grep dev | sort | head -1` \
        `apt-cache pkgnames libsqlite3 | grep dev | sort -V | head -1` \
        `apt-cache pkgnames libwebp | grep dev | sort -V | head -1` \
        `apt-cache pkgnames libzip | grep dev | sort | head -1` \
        `apt-cache pkgnames licurl4 | grep dev | grep openssl | sort -V` \
        `apt-cache pkgnames unixodbc | grep dev | sort -V | head -1` \
        `apt-cache pkgnames zlib | grep dev | sort -V | head -1` \
    && update-ca-certificates; \
    export \
		CFLAGS="$PHP_CFLAGS" \
		CPPFLAGS="$PHP_CPPFLAGS" \
		LDFLAGS="$PHP_LDFLAGS" \
    ; \
\
# Install PHP extensions from source using PECL \
    pecl install --onlyreqdeps --nobuild igbinary; \
        cd "$(pecl config-get temp_dir)/igbinary"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable --ini-name 0-docker-php-ext-igbinary.ini igbinary; \
    pecl install --onlyreqdeps --nobuild msgpack; \
        cd "$(pecl config-get temp_dir)/msgpack"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable --ini-name 0-docker-php-ext-msgpack.ini msgpack; \
    pecl install --onlyreqdeps --nobuild sqlsrv; \
        cd "$(pecl config-get temp_dir)/sqlsrv"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable sqlsrv; \
    pecl install --onlyreqdeps --nobuild pdo_sqlsrv; \
        cd "$(pecl config-get temp_dir)/pdo_sqlsrv"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable pdo_sqlsrv; \
    pecl install --onlyreqdeps --nobuild xhprof; \
        cd "$(pecl config-get temp_dir)/xhprof/extension"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable xhprof; \
\
# Install PHP extensions built into the official image \
    docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype --with-avif; \
    docker-php-ext-install -j"$(nproc)" \
        bcmath \
        dba \
        gd \
        gettext \
        intl \
        mysqli \
        pcntl \
        pdo \
        pdo_mysql \
        pdo_sqlite \
        sockets \
        zip; \
    \
# Install additional PHP extensions using PIE for easier management and to get the latest stable versions \
    pie install --skip-enable-extension apcu/apcu  && \
    pie install --skip-enable-extension imagick/imagick && \
    pie install --skip-enable-extension nikic/php-ast  && \
    pie install --skip-enable-extension osmanov/pecl-ev  && \
    pie install --skip-enable-extension pecl/mcrypt  && \
    pie install --skip-enable-extension pecl/pcov  && \
    pie install --skip-enable-extension php-memcached/php-memcached --enable-memcached-json --enable-memcached-igbinary --enable-memcached-msgpack  && \
    pie install --skip-enable-extension phpredis/phpredis --enable-redis-igbinary --enable-redis-msgpack  && \
    pie install --skip-enable-extension swoole/swoole  && \
    pie install --skip-enable-extension xdebug/xdebug  && \
    docker-php-ext-enable apcu \
      imagick \
      ast \
      ev \
      mcrypt \
      pcov \
      memcached \
      redis \
      swoole \
      xdebug ; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies \
    apt-mark auto '.*' > /dev/null; \
    [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark; \
    find /usr/local -type f -executable -exec ldd '{}' ';' \
        | awk '/=>/ { so = $(NF-1); if (index(so, "/usr/local/") == 1) { next }; gsub("^/(usr/)?", "", so); printf "*%s\n", so }' \
        | sort -u \
        | xargs -rt dpkg-query --search \
# https://manpages.debian.org/trixie/dpkg/dpkg-query.1.en.html#S (we ignore diversions and it'll be really unusual for more than one package to provide any given .so file) \
        | awk 'sub(":$", "", $1) { print $1 }' \
        | sort -u \
        | xargs -r apt-mark manual \
    ; \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    apt-get dist-clean; \
    \
# update pecl channel definitions https://github.com/docker-library/php/issues/443 \
    pecl update-channels; \
    rm -rf /tmp/pear ~/.pearrc; \
    \
# smoke test \
    php -m; \
# remove all extensions by default except for igbinary and msgpack \
    rm -rf $PHP_INI_DIR/conf.d/docker-php-ext-*.ini; \
    rm -rf /tmp/* ~/.pearrc /var/lib/apt/lists/* /var/cache/*; \
# re-enable default extensions by official image \
    docker-php-ext-enable sodium opcache; \
# copy envsubst for easier use in entrypoint scripts \
    cp /usr/bin/envsubst /usr/local/bin/envsubst; \
    mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s/;emergency_restart_threshold\s*=\s*.*/emergency_restart_threshold = 10/g" $PHP_INI_DIR/../php-fpm.conf \
    ; sed -i "s/;emergency_restart_interval\s*=\s*.*/emergency_restart_interval = 1m/g" $PHP_INI_DIR/../php-fpm.conf \
    ; sed -i "s/;process_control_timeout\s*=\s*.*/process_control_timeout = 10s/g" $PHP_INI_DIR/../php-fpm.conf \
    ;

WORKDIR /var/www/html
CMD ["php-fpm"]