ARG PHP_VERSION=8
FROM php:${PHP_VERSION}-cli-alpine
LABEL org.opencontainers.image.description="PHP base image with commonly used extensions pre-installed" \
     "com.koalaphils.vendor"="Koala Software Technology Innovations" \
     "com.koalaphils.image.author"="mdprotacio@outlook.com"

COPY --from=ghcr.io/php/pie:bin /pie /usr/bin/pie
ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_PROCESS_TIMEOUT=600

ENV PHPIZE_DEPS \
    $PHPIZE_DEPS \
# Add dependencies for PIE \
    autoconf \
    automake \
    gcc \
    git \
    libtool \
    m4 \
    make \
# Add helper tools for development \
    gettext \
    netcat-openbsd \
    wget

# Install dependencies
RUN set -eux; \
    apk update; \
    apk add --no-cache \
        $PHPIZE_DEPS \
        freetype \
        icu \
        imagemagick-libs \
        libavif \
        libjpeg-turbo \
        libmcrypt \
        libmcrypt \
        libmemcached-libs \
        libpng \
        libwebp \
        libzip \
        msgpack-c \
        unixodbc \
        zlib \
    ;

RUN set -eux; \
    apk add --no-cache --virtual .build-deps \
        $PHPIZE_DEPS \
        freetype-dev \
        gettext-dev \
        icu-dev \
        imagemagick-dev \
        jpeg-dev \
        libavif-dev \
        libmcrypt-dev \
        libmemcached-dev \
        libpng-dev \
        libwebp-dev \
        libzip-dev \
        linux-headers \
        unixodbc-dev \
        zlib-dev \
    ; \
# Install PHP extensions from source using PECL \
    pecl install --onlyreqdeps --nobuild igbinary; \
        cd "$(pecl config-get temp_dir)/igbinary"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable --ini-name 0-docker-php-ext-igbinary.ini igbinary; \
    pecl install --onlyreqdeps --nobuild msgpack; \
        cd "$(pecl config-get temp_dir)/msgpack"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
        docker-php-ext-enable --ini-name 0-docker-php-ext-msgpack.ini msgpack; \
    pecl install --onlyreqdeps --nobuild sqlsrv; \
        cd "$(pecl config-get temp_dir)/sqlsrv"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
    pecl install --onlyreqdeps --nobuild pdo_sqlsrv; \
        cd "$(pecl config-get temp_dir)/pdo_sqlsrv"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
    pecl install --onlyreqdeps --nobuild xhprof; \
        cd "$(pecl config-get temp_dir)/xhprof/extension"; \
        phpize; \
        ./configure; \
        make && make test && make install && make clean || exit 1; \
        cd -; \
\
# Install PHP extensions built into the official image \
    docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype --with-avif; \
    docker-php-ext-install -j"$(nproc)" \
        bcmath \
        dba \
        gd \
        gettext \
        intl \
        mysqli \
        pdo_mysql \
        pcntl \
        sockets \
        zip; \
    \
# Install additional PHP extensions using PIE for easier management and to get the latest stable versions \
    pie install apcu/apcu --skip-enable-extension; \
    pie install phpredis/phpredis --enable-redis-igbinary --enable-redis-msgpack --skip-enable-extension; \
    pie install php-memcached/php-memcached --enable-memcached-igbinary --enable-memcached-msgpack --skip-enable-extension; \
    pie install xdebug/xdebug --skip-enable-extension; \
    pie install osmanov/pecl-ev --skip-enable-extension; \
    pie install pecl/pcov --skip-enable-extension; \
    pie install nikic/php-ast --skip-enable-extension; \
    pie install swoole/swoole --skip-enable-extension; \
    pie install pecl/mcrypt --skip-enable-extension; \
    pie install imagick/imagick --skip-enable-extension; \
    \
# Cleanup \
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --no-cache $runDeps; \
	\
	apk del --no-network .build-deps; \
	\
# update pecl channel definitions https://github.com/docker-library/php/issues/443
	pecl update-channels; \
	rm -rf /tmp/pear ~/.pearrc; \
	\
# smoke test
	php -m \
# remove all extensions by default except for igbinary and msgpack \
    rm -rf $PHP_INI_DIR/conf.d/docker-php-ext-*.ini; \
    rm -rf /tmp/* ~/.pearrc /var/lib/apt/lists/* /var/cache/*; \
# re-enable default extensions by official image \
    docker-php-ext-enable sodium opcache; \
# copy envsubst for easier use in entrypoint scripts \
    cp /usr/bin/envsubst /usr/local/bin/envsubst; \
    mv $PHP_INI_DIR/php.ini-production $PHP_INI_DIR/php.ini \
    ; sed -i "s|^expose_php\s*=\s*\(.*\)|expose_php=Off|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_size\s*=\s*\(.*\)|realpath_cache_size=\2|g" $PHP_INI_DIR/php.ini \
    ; sed -i "s|^\(;\)*realpath_cache_ttl\s*=\s*\(.*\)|realpath_cache_ttl=\2|g" $PHP_INI_DIR/php.ini \
    ;

WORKDIR /var/www/html
CMD ["php", "-a"]
